baseURL = "https://theproposalstack.com/"
languageCode = "en-us"
title = "The Proposal Stack"
theme = "PaperMod"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
  
[taxonomies]

[params]
  description = "Proposal mechanics, translated for technical GovCon professionals"
  author = "Jerome Bridges"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  disableSpecial1stPost = true
  hideFooter = true

[params.homeInfoParams]
  Title = "The Proposal Stack"
  Content = "Proposal mechanics, translated for technical GovCon professionals."

[[params.socialIcons]]
  name = "email"
  url = "mailto:editor@theproposalstack.com"

[menu]
  [[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Subscribe"
    url = "https://read.theproposalstack.com"
    weight = 30